server:
  mvc:
    favicon:
      enabled: true
spring:
  message:
    welcome: Spring Boot Live-Repload with Dockerfile!!
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /stats